version: "3.8"
services:
  database:
    image: postgres:14
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: ts-express-app
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: testdb
    volumes:
      - .:/usr/src/app
    command: [ "npm", "run", "start:prod" ]

volumes:
  db_data:
